version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: currency_converter
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    restart: unless-stopped
    networks:
      - currency_converter_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p", "admin"]
      interval: 20s                     #Tiempo entre cada chequeo
      retries: 20                       #Numero de intentos antes de marcarlo como unhealth
      start_period: 60s                 #Tiempo inicial antes de que empiecen los chequeos
      timeout: 5s                       #Maximo tiempo qe se espera antes de fallar un chequeo


networks:
  currency_converter_network:
    driver: bridge
    name: currency_converter_network

volumes:
  mysql_data:
    name: mysql_data